	AREA RESET, DATA, READONLY
	EXPORT __Vectors

__Vectors
    DCD 0x10001000      ; STACK POINTER VALUE WHEN STACK IS EMPTY
    DCD Reset_Handler   ; RESET VECTOR

	ALIGN
	AREA mycode, CODE, READONLY
ENTRY
	EXPORT Reset_Handler

Reset_Handler
	LDR R0, =src
	LDR R1,[R0]
	MOV R2,#0xA
BACK
	SUB R1,R2
	ADD R3,#1
	CMP R1,R2
	BCS BACK
	LSL R3,#4
	ORR R9,R1,R3
	LDR R4,=DST
	STR R9,[R4],#4
src DCD 0x0000004A
STOP B STOP
	AREA data, DATA, READWRITE
DST DCD 0,0,0,0,0,0,0,0,0
	END